#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
#Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL.
# USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO

while ifs=: read -r c1 c2 c3 c4 c5 c6 c7; do
  echo "The user $c1 is part of the $c4 gang, lives in $c6 and rides $c7. $c3's place is protected by the passcode $c2, more info about the user here: $c5"

done</etc/passwd
