#!/usr/bin/env bash
#display best school 10 times on the 9th iteration display "Best School Hi"
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ];  then
	echo "Best School"  "Hi"
	fi
	i=$((i+1))
done
